### PR TITLE
to avoid warnings

### PR DESCRIPTION
**Pull request by wheeOs**
these warnings appeared:

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:42:29: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/tools/flutter/packages/flutter/lib/src/widgets/binding.dart').
    _state = WidgetsBinding.instance!.lifecycleState;
                            ^
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:43:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/tools/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart:52:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/tools/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);

### CODE REVIEW

**Comment by noga-dev** [comment]
Because you're on the master branch.

**Comment by rrousselGit** [comment]
Thanks!
I'll delay the merge of this until it's available in stable

Could you also update the pubspec.yaml flutter constraints to be >= 2.14.0-0.0.pre.306?

**Comment by wheeOs** [comment]
@rrousselGit do you mean the pubspec.yaml from the flutter_hooks project?

**Comment by rrousselGit** [comment]
Yes

**Comment by wheeOs** [comment]
done

**Pull request merged**
