### PR TITLE
Example Gallery

### PR DESCRIPTION
**Pull request by brianegan**
Hey hey -- I wanted to play with hooks and get a feel for them. 

I started creating a couple of one-off examples and my own hooks to internalize the concepts and ended up creating a kind of Gallery.

I decided this might be a nice addition to the repo. It's incomplete, but I can add more examples and much more documentation if this looks like something you're interested in!

## Todo

  - [ ] Update README
  - [ ] Add documentation for each step of each example
  - [ ] Example Functional Hook
  - [ ] Example Class-based Hook
  - [ ] useMemoized
  - [ ] useStreamController & Friends
  - [ ] useAnimationController & Friends

### CODE REVIEW

**Comment by rrousselGit** [comment]
Awesome, I love the idea!
A lot of examples is what's missing to the project.


I think it would be interesting to split this into multiple PR though. One for the gallery itself, and one per example. So that I can work on some example simultaneously with you

**Comment by brianegan** [comment]
I dig it. I'll go ahead and clean up what I've got and we can use that as the starting point for the gallery.

**Comment by rrousselGit** [comment]
Following this, do you think it would be interesting to add a "vanilla hooks" to Flutter architecture samples?

**Comment by brianegan** [comment]
Definitely! It'd be very interesting to see how it changes the app architecture. I could see a scenario where hooks play a "lighter" role to create Blocs, Presenters, etc, or a more active Role where they contain more business logic. Since they're quite a new concept, it would be fun to play with both directions.

Anyhow, visiting family and traveling for just a couple more days! I'll clean get back to this PR on Thursday or Friday :)

**Comment by rrousselGit** [comment]
Cool, I'll give it a try!

BTW I would heavily recommend using  https://github.com/rrousselGit/functional_widget in the process while working on some examples. They are meant to be used together. So that we're going from:

```dart
class Foo extends StatefulWidget {
  @override
  _FooState createState() => _FooState();
}

class _FooState extends State<Foo>
    with SingleTickerProviderStateMixin {
  AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

to:

```dart
@hwidget
Widget foo() {
  final animationController = useAnimationController();
  return Container();
}
```

**Comment by brianegan** [comment]
Hey hey -- found a little bit of time to update this code, mostly small cleanup and adding documentation to help folks understand what the code is doing.

Does this look Ok as a starting point? It's a bit more filled out than what is currently available, but does not yet make use of `function_widget`.

**Comment by rrousselGit** [comment]
> One recommendation: Right now the android and ios directories are ignored.

I typically use `flutter create .` for this, which bootstraps everything at once.
I'm not necessarily against it, but they don't bring any value to the example.

**Comment by rrousselGit** [comment]
Well since to run the example you have to do a `flutter packages get`, but that `flutter create .` does that `packages get` internally, then it really doesn't change much.

**Comment by rrousselGit** [comment]
Nice one on adding it in the readme. Obvious but I didn't think of it! 👌

**Comment by brianegan** [comment]
> Well since to run the example you have to do a flutter packages get, but that flutter create . does that packages get internally, then it really doesn't change much.

Yep, it's just a `flutter run` vs a `flutter create .` + `flutter run`. IntellIJ also makes all of this automatic for ya if the android and ios folders are place, which is why I noticed it (I often just open a project and hit "Run" and everything Just Works, but didn't for this repo).

**Comment by brianegan** [comment]
Looks like the build passed! When you get a chance, please let me know if this needs any further changes :)

**Comment by Solido** [comment]
I've been waiting for this !

**Comment by rrousselGit** [comment]
image

**Comment by rrousselGit** [comment]
Nice job! It's a good starter!

We will definitely need to write some tests for these examples though (which make tests an example by themselves).

**Pull request merged**
